"""
run_sql_queries.py — Phase 5: run the 10 analysis queries against RDS
==================================================================================
Parses sql/02_analysis_queries.sql, runs each query, prints the result table, and
writes a results section to docs/BUSINESS_INSIGHTS.md.
==================================================================================
"""

import os
import re
import sys
import logging

import pandas as pd
import psycopg2
from dotenv import load_dotenv

sys.stdout.reconfigure(encoding="utf-8")
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)
load_dotenv()

SQL_FILE = os.path.join("analysis", "sql", "queries.sql")
OUT_MD = os.path.join("docs", "BUSINESS_INSIGHTS.md")


def get_connection():
    return psycopg2.connect(
        host=os.getenv("RDS_HOST"),
        port=int(os.getenv("RDS_PORT", 5432)),
        database=os.getenv("RDS_DATABASE"),
        user=os.getenv("RDS_USERNAME"),
        password=os.getenv("RDS_PASSWORD"),
        connect_timeout=15,
    )


def parse_queries(path):
    text = open(path, encoding="utf-8").read()
    blocks = re.split(r"\n(?=-- Q\d+:)", text)
    out = []
    for b in blocks:
        b = b.strip()
        if not re.match(r"-- Q\d+:", b):
            continue
        lines = b.split("\n")
        title = lines[0].lstrip("- ").strip()
        sql = "\n".join(ln for ln in lines if not ln.strip().startswith("--")).strip().rstrip(";")
        out.append((title, sql))
    return out


def df_to_md(df):
    cols = [str(c) for c in df.columns]
    header = "| " + " | ".join(cols) + " |"
    sep = "| " + " | ".join(["---"] * len(cols)) + " |"
    rows = ["| " + " | ".join(str(v) for v in row) + " |" for row in df.itertuples(index=False)]
    return "\n".join([header, sep] + rows)


def main():
    queries = parse_queries(SQL_FILE)
    logger.info(f"Parsed {len(queries)} queries")
    conn = get_connection()
    md = ["# HOSPIQ — SQL Query Results",
          "",
          "_Generated by `python/run_sql_queries.py` against RDS PostgreSQL._", ""]
    try:
        for title, sql in queries:
            df = pd.read_sql_query(sql, conn)
            print("=" * 78)
            print(title)
            print("-" * 78)
            print(df.to_string(index=False))
            print()
            md += [f"## {title}", "", df_to_md(df), ""]
    finally:
        conn.close()
    open(OUT_MD, "w", encoding="utf-8").write("\n".join(md))
    logger.info(f"Wrote results to {OUT_MD}")


if __name__ == "__main__":
    main()
